# Generated by Django 5.1.5 on 2025-03-05 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', '⏳ Kutmoqda'), ('present', '✔ Bor'), ('absent', '❌ Yo‘q')], default='pending', max_length=10)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='najot.data')),
            ],
        ),
    ]
