# Generated by Django 5.1.5 on 2025-03-05 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('najot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='najot.data'),
        ),
    ]
